threads:
  fastp: 8
  star: 16
  samtools: 8
  featurecounts: 8
  deeptools: 8

reference:
  # STAR genome index folder (must be prebuilt, e.g. contains SA file)
  star_index: "resources/reference/star_index"
  fasta: "resources/reference/genome.fa"
  gtf: "resources/reference/genes.gtf"
  # Chromosome sizes file (2 columns: chrom, size). If omitted, <reference.fasta>.fai is used.
  chrom_sizes: "resources/reference/genome.fa.fai"

samples:
  sampleA:
    R1:
      - "raw/sampleA_L001_R1.fastq.gz"
      - "raw/sampleA_L002_R1.fastq.gz"
    R2:
      - "raw/sampleA_L001_R2.fastq.gz"
      - "raw/sampleA_L002_R2.fastq.gz"

  sampleB:
    R1:
      - "raw/sampleB_R1.fastq.gz"
    R2:
      - "raw/sampleB_R2.fastq.gz"

fastp:
  # dedup + adapter trimming
  dedup_adapter:
    dedup: true


output:
  dir: "results"
  # keep STAR BAM files after pipeline finishes
  keep_bam: false

bigwig:
  bin_size: 10
  normalization: "RPKM"
  remove_chrM_and_scaffolds: true
